version: 2.0

jobs:
  build:
    docker:
      - image: alpine:3.10.2

    steps:
      - checkout

      - run:
          name: Prepare
          command: apk add -u --no-progress make autoconf automake g++ m4 libtool libev-dev check-dev

      - run:
          name: Autoconf
          command: autoreconf --install

      - run:
          name: Configure
          command: ./configure

      - run:
          name: Build
          command: make

      - run:
          name: Check
          command: make check

  publish:
    docker:
      - image: alpine:3.10.2

    steps:
      - checkout

      - run:
          name: Command
          command: |
            echo "I'll publish the artifact"

workflows:
  version: 2
  build:
    jobs:
      - build

      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^version-\d+\.\d+\.\d+$/
