version: 2
jobs:
  build:
    docker:
      - image: alpine:3.10.2

    steps:
      - checkout

      - run:
          name: Prepare
          command: apk add -u --no-progress make autoconf automake g++ m4 libtool libev-dev check-dev

      - run:
          name: Autoconf
          command: autoreconf --install

      - run:
          name: Configure
          command: ./configure

      - run:
          name: Build
          command: make

      - run:
          name: Check
          command: make check
