version: 2
jobs:
  build:
    docker:
      - image: alpine:3.10.2

    steps:
      - checkout

      - run:
          name: Prepare
          command: apk upgrade; apk update; apk add autoconf gcc libev-dev

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Autoconf
          command: autoreconf --install

      - run:
          name: Configure
          command: ./configure

      - run:
          name: Build
          command: make

      - run:
          name: Check
          command: make check
